<?php
/**
 * Created by PhpStorm.
 * User: bianl
 * Date: 2019/2/21
 * Time: 9:50
 */
namespace app\admin\controller;
use think\Controller;

class BaseController extends Controller{
    //  主要功能：Sentinel，安全检查。
    //  应对case：当有人试图利用路径进入管理员列表时，即在url中进入User控制器的list方法（admin/User/list）。
    //  User控制器继承此Base控制器 => 执行初始化函数（方法）=> 函数中判断session中是否有值
    //  => session没有值说明没有登陆，跳转登陆界面。

    public function _initialize()
    {
        //  Controller类的初始函数，在创建controller实例时先执行此函数。
        parent::_initialize(); // TODO: Change the autogenerated stub
        if(!session('name')){
            $this->error("请先登陆系统！","Index/login");
        }
    }
}